name: ui_lib
version: 1.0.1
author: Andrriy Kemin
description: A UI library app.
environment:
  sdk: 1.3.0
documentation: Small UI Library based on Polymer
dependencies:
  animation: any
  polymer: any
transformers:
- polymer:
    entry_points: web/test.html
